name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
        sudo apt install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm
        sudo apt install -y libncurses5-dev libncursesw5-dev xz-utils tk-dev unzip
        sudo apt install -y zlib1g-dev autoconf automake libtool expect
        sudo apt install -y lsb-release libtool-bin pkg-config cmake
        sudo apt install -y libltdl-dev gettext

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.33
        pip install kivy==2.3.1
        pip install kivymd==1.2.0
        pip install buildozer==1.5.0
        pip install requests==2.31.0 plyer==2.1.0 pillow==9.3.0
        pip install https://github.com/MichaelStott/KivMob/archive/refs/heads/master.zip

    - name: Setup Android SDK licenses
      run: |
        mkdir -p $HOME/.android/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.android/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $HOME/.android/licenses/android-sdk-license

    - name: Build APK
      run: |
        export JAVA_HOME=$JAVA_HOME
        buildozer android debug --verbose

    - name: Upload APK
      run: |
        mkdir -p output
        APK_FILE=$(find . -name "*.apk" -type f | head -1)
        if [ -n "$APK_FILE" ]; then
          cp "$APK_FILE" output/snake-game.apk
          echo "✅ APK created successfully!"
        else
          echo "❌ No APK found"
          exit 1
        fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: output/snake-game.apk
