name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-8-jdk build-essential libssl-dev libffi-dev python3-dev
        sudo apt install -y libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm
        sudo apt install -y libncurses5-dev libncursesw5-dev xz-utils tk-dev
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.33
        pip install -r requirements.txt

    - name: Accept Android SDK licenses
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export ANDROID_HOME="$HOME/.buildozer/android/platform/android-sdk"
        mkdir -p "$ANDROID_HOME/licenses" || true
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

    - name: Build APK with Buildozer
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: snake-game-apk
        path: bin/*.apk
